name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v13
        with:
          name: claude-code-nvim
          skipPush: ${{ github.event_name == 'pull_request' }}
      - name: Run formatting check
        run: nix flake check
      - name: Run tests
        run: nix develop --command just test
      - name: Run linter
        run: nix develop --command just lint
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting
        run: nix fmt -- --fail-on-change
